using System;
using Hawkynt.RandomNumberGenerators.Composites;

namespace Hawkynt.RandomNumberGenerators.NonUniform;

/// <summary>
///   Log-normal distribution: a continuous distribution whose logarithm is normally
///   distributed. Used wherever multiplicative effects compound — biological growth,
///   stock prices, income distributions, particle sizes.
/// </summary>
/// <remarks>
///   Generated by sampling a standard normal Z and returning exp(mu + sigma·Z).
/// </remarks>
public class Lognormal {
  private readonly ArbitraryNumberGenerator _generator;
  private readonly double _mu;
  private readonly double _sigma;

  public Lognormal(ArbitraryNumberGenerator generator, double mu = 0.0, double sigma = 1.0) {
    ArgumentNullException.ThrowIfNull(generator);
    ArgumentOutOfRangeException.ThrowIfLessThanOrEqual(sigma, 0.0);
    this._generator = generator;
    this._mu = mu;
    this._sigma = sigma;
  }

  public double Next() {
    var z = _StandardNormal(this._generator);
    return Math.Exp(this._mu + this._sigma * z);
  }

  private static double _StandardNormal(ArbitraryNumberGenerator generator) {
    for (;;) {
      var x = 2.0 * generator.NextDouble() - 1.0;
      var y = 2.0 * generator.NextDouble() - 1.0;
      var s = x * x + y * y;
      if (s is <= 0.0 or >= 1.0)
        continue;
      return x * Math.Sqrt(-2.0 * Math.Log(s) / s);
    }
  }
}
